### ISSUE TITLE
spurious error module not found

### ISSUE THREAD

**Issue by kohlhase** [slatex/sTeX-IDE#3] opened 2022-09-01 07:39 UTC
I get various spurious errors about modules not found, e.g. 
<img width="589" alt="Screenshot 2022-09-01 at 09 37 49" src="https://user-images.githubusercontent.com/4037538/187859072-ff99fac3-00d0-4464-8669-9258654fbbe7.png">

the module is really there. I suspect that this is a linter problem

**Comment by kohlhase** [comment] 2022-09-01 07:45
Hmmm, this might also be a consequence of the fact that the linter things that the module `valuation?fo-valuation` has an error. It things that an sproof does not close
<img width="647" alt="Screenshot 2022-09-01 at 09 44 07" src="https://user-images.githubusercontent.com/4037538/187860156-1c80d7da-f46d-48fb-9efb-2d414740a9b6.png">
And that seems to be the case as there is a linebreak in the optional argument, when I remove that, the problem goes away. 
<img width="794" alt="Screenshot 2022-09-01 at 09 45 09" src="https://user-images.githubusercontent.com/4037538/187860370-af9b7ad2-a465-4b1e-b734-37c4acc1d15c.png">

**Comment by Jazzpirate** [comment] 2022-09-01 08:21
This is especially weird in that the linter currently has no special support for sproof at all - it shouldn't even care about the optional arguments...

**Comment by kohlhase** [comment] 2022-09-01 11:22
I think the analysis above is wrong, the errors re-appeared after a while.
BUT `valuation.en.tex` still shows 5 errors that I cannot find (have tried a lot). 
@Jazzpirate could you have a look what's wrong (pdflatex works).

**Comment by Jazzpirate** [comment] 2022-09-01 12:38
Cannot reproduce. Can you post the precise error message for the red underlined part?

**Comment by Jazzpirate** [comment] 2022-09-01 13:05
> Cannot reproduce. Can you post the precise error message for the red underlined part?

Nevermind, managed to reproduce. Will investigate

**Comment by Jazzpirate** [comment] 2022-09-01 13:11
Found the error. No idea why that works in pdflatex, tbh - there's clearly an open brace which isn't closed properly in line 84, col 50, it's nonsensically closed in line 85 instead.

I'd expect that to be a tex error - if you open a brace in math mode, it should close before the math mode is closed. I suspect that some other brace is closed instead (tex checks that group delimiters match, i.e. a group opened by $ needs to be closed by $, a group opened by { must be closed by } etc.), leading to errors that just happen to be output neutral.

I consider this to be a feature of the linter, not a bug :D

**Closed** 2022-09-01 13:14 UTC
Labels: bug
